import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const armenianFont = localFont({
  src: "../public/fonts/Vrdznagir.otf",
  variable: "--font-armenian",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${armenianFont.className} min-h-full relative flex flex-col bg-background text-foreground justify-center items-center`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
